const foodTruckData = [
  {
    id: 1,
    title: 'Braai on Wheels',
    description: 'Sizzling braai delights on the go.',
    imageUrl: 'truck1.jpg',
    cuisineType: ['Shisa Nyama', 'Beef Stew', 'Pap and Steak'],
    rating: 4.5,
  },
  {
    id: 2,
    title: 'Tselanes Kitchen',
    description: 'Hearty home-style stews and sides.',
    imageUrl: 'truck2.jpg',
    cuisineType: ['Beef Stew', 'Comfort Food', 'Vegetables'],
    rating: 3.8,
  },
  {
    id: 3,
    title: 'Hangry Chef',
    description: 'Gourmet comfort eats to satisfy any craving.',
    imageUrl: 'truck3.jpg',
    cuisineType: ['Comfort Food', 'Fast Food', 'Chips'],
    rating: 4.7,
  },
  {
    id: 4,
    title: 'Bites on the Move',
    description: 'Local favourites with a tasty twist.',
    imageUrl: 'truck4.jpg',
    cuisineType: ['Smileys', 'Walkie Talkies', 'Kota'],
    rating: 4.1,
  },
  {
    id: 5,
    title: 'CraveWave Canteen',
    description: 'Loaded kotas and other street food classics.',
    imageUrl: 'truck5.jpg',
    cuisineType: ['Kota', 'Chips', 'Fast Food'],
    rating: 4.2,
  },
  {
    id: 6,
    title: 'HungryRolls on Wheels',
    description: 'Bunny chow and boere rolls done right.',
    imageUrl: 'truck6.jpg',
    cuisineType: ['Bunny Chow', 'Boere Rolls', 'Comfort Food'],
    rating: 4.8,
  },
  {
    id: 7,
    title: 'StreetFare Serenade',
    description: 'Traditional pap and steak, cooked to perfection.',
    imageUrl: 'truck7.jpg',
    cuisineType: ['Pap and Steak', 'Shisa Nyama', 'Vegetables'],
    rating: 5.0,
  },
  {
    id: 8,
    title: 'NomNom Nomads',
    description: 'Boere rolls with a variety of fillings.',
    imageUrl: 'truck8.jpg',
    cuisineType: ['Boere Rolls', 'Fast Food', 'Light Meals'],
    rating: 5.0,
  },
  {
    id: 9,
    title: 'Culinary Chaos',
    description: 'Rich and hearty beef stews for cold days.',
    imageUrl: 'truck9.jpg',
    cuisineType: ['Beef Stew', 'Comfort Food', 'Vegetables'],
    rating: 4.9,
  },
  {
    id: 10,
    title: 'Foodys Fantasy',
    description: 'Wholesome beef stews and sides to warm you up.',
    imageUrl: 'truck10.jpg',
    cuisineType: ['Beef Stew', 'Comfort Food', 'Vegetables'],
    rating: 5.0,
  },
  {
    id: 11,
    title: 'Streat Cuisine',
    description: 'Spicy walkie talkies and smileys for the daring.',
    imageUrl: 'truck11.jpg',
    cuisineType: ['Smileys', 'Walkie Talkies', 'African'],
    rating: 3.6,
  },
  {
    id: 12,
    title: 'Durbs Finest Curry',
    description: 'Authentic Durban bunny chow and curries.',
    imageUrl: 'truck12.jpg',
    cuisineType: ['Bunny Chow', 'Comfort Food', 'African'],
    rating: 4.9,
  },
  {
    id: 13,
    title: 'Feedrite',
    description: 'Tasty smileys and walkie talkies, cooked fresh.',
    imageUrl: 'truck13.jpg',
    cuisineType: ['Smileys', 'Walkie Talkies', 'African'],
    rating: 4.8,
  },
  {
    id: 14,
    title: 'Flippin Spree',
    description: 'A feast of local street food delights.',
    imageUrl: 'truck14.jpg',
    cuisineType: ['Kota', 'Smileys', 'Walkie Talkies'],
    rating: 4.5,
  },
  {
    id: 15,
    title: 'Flyin Fries',
    description: 'Crispy chips and classic fish & chips.',
    imageUrl: 'truck15.jpg',
    cuisineType: ['Fast Food', 'Fish & Chips', 'Chips'],
    rating: 3.8,
  },
  {
    id: 16,
    title: 'Chic-en-Chilli',
    description: 'Spicy chicken dishes and comfort meals.',
    imageUrl: 'truck16.jpg',
    cuisineType: ['Chicken', 'Comfort Food', 'Fast Food'],
    rating: 5.0,
  },
];

export default foodTruckData;