const foodTruckData = [
  {
    id: 1,
    title: 'The Burger Joint',
    description: 'Delicious burgers and fries.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Shisa Nyama',
    rating: 4.5,
  },
  {
    id: 2,
    title: 'Taco Time',
    description: 'Authentic Mexican tacos.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Beef Stew',
    rating: 3.8,
  },
  {
    id: 3,
    title: 'Pizza Palace',
    description: 'Wood-fired pizzas.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Beef Stew',
    rating: 4.2,
  },
  {
    id: 4,
    title: 'Pizza Palace',
    description: 'Wood-fired pizzas.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Smileys',
    rating: 4.2,
  },
  {
    id: 5,
    title: 'Pizza Palace',
    description: 'Wood-fired pizzas.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Kota',
    rating: 4.2,
  },
  {
    id: 6,
    title: 'Pizza Palace',
    description: 'Wood-fired pizzas.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Bunny Chow',
    rating: 4.2,
  },
  {
    id: 7,
    title: 'Pizza Palace',
    description: 'Wood-fired pizzas.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Pap',
    rating: 4.2,
  },
  {
    id: 8,
    title: 'Pizza Palace',
    description: 'Wood-fired pizzas.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Boere Rolls',
    rating: 4.2,
  },
  {
    id: 9,
    title: 'Pizza Palace',
    description: 'Wood-fired pizzas.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Beef Stew',
    rating: 3.1,
  },
  {
    id: 10,
    title: 'Pizza Palace',
    description: 'Wood-fired pizzas.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Beef Stew',
    rating: 4.2,
  },
  {
    id: 11,
    title: 'Pizza Palace',
    description: 'Wood-fired pizzas.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Mala',
    rating: 4.2,
  },
  {
    id: 12,
    title: 'Pizza Palace',
    description: 'Wood-fired pizzas.',
    imageUrl: 'placeholder-image.jpg',
    cuisineType: 'Mala',
    rating: 4.2,
  },
  // ... more food trucks
];

export default foodTruckData;